build-docker:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/.ci"
      --dockerfile "${CI_PROJECT_DIR}/.ci/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:pages-${CI_COMMIT_REF_NAME}"
  rules:
    # Run on changes to the CI directory only.
    - changes:
        - .ci/**/*
        - .gitlab-ci.yml

trigger-pages:
  stage: deploy
  script:
    - curl -X POST -F token=$TRIGGER_PAGES_TOKEN -F ref=gitlab-pages https://gitlab.com/api/v4/projects/40691572/trigger/pipeline
